apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-configmap
  namespace: evaluation-service
data:
  FLAG_SERVICE_URL: http://flag-service.flag-service
  TARGETING_SERVICE_URL: http://targeting-service.targeting-service
