apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: evaluation-service
type: Opaque
stringData:
  REDIS_URL: redis://redis.infrastructure.svc.cluster.local:6379
  AWS_SQS_URL: http://elasticmq.infrastructure.svc.cluster.local:9324/000000000000/analytics-queue
  AWS_REGION: us-east-1
  SERVICE_API_KEY: "local-dev-key"
  AWS_ACCESS_KEY_ID: dummy
  AWS_SECRET_ACCESS_KEY: dummy
  AWS_SESSION_TOKEN: ""
