apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: evaluation-service
type: Opaque
stringData:
  REDIS_URL: redis://toggle-feature-redis.rlmbw8.0001.use1.cache.amazonaws.com:6379
  AWS_SQS_URL: https://sqs.us-east-1.amazonaws.com/550829113486/evaluation-queue
  AWS_REGION: us-east-1
  SERVICE_API_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""



