apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: targeting-service
type: Opaque
stringData:
  DATABASE_URL: postgres://targeting_user:targeting_pass@postgres-targeting.infrastructure.svc.cluster.local:5432/targeting_db
