apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: flag-service
type: Opaque
stringData:
  DATABASE_URL: postgres://flag:flag@postgres-flag.infrastructure.svc.cluster.local:5432/flags
