apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 1024
        timeout: 10s
      resource:
        attributes:
          - action: upsert
            key: deployment.environment
            value: production

    exporters:
      otlp/newrelic:
        endpoint: otlp.nr-data.net:4317
        headers:
          api-key: "${env:NEW_RELIC_LICENSE_KEY}"

      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
        tls:
          insecure: true

      loki:
        endpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        default_labels_enabled:
          exporter: false
          job: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp/newrelic]
        metrics:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp/newrelic, prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp/newrelic, loki]
