version: '3.9'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    env_file:
      - .env
    volumes:
      - ./otel-collector-config.yml:/etc/otel/config.yml
    command: ["--config=/etc/otel/config.yml"]
    networks:
      - toggle-network

networks:
  toggle-network:
    driver: bridge