apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/toggle-feature-terraform
    path: GitOps/flag-service
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: flag-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
