apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
type: Opaque
stringData:
  DATABASE_URL: postgres://auth:auth@postgres-auth.infrastructure.svc.cluster.local:5432/auth
  MASTER_KEY: supersecretmasterkey
